# Generated by Django 4.2.5 on 2023-09-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='list',
        ),
        migrations.AddField(
            model_name='movie',
            name='list',
            field=models.ManyToManyField(default=None, to='movies.list'),
        ),
    ]
