# Generated by Django 4.2.5 on 2023-09-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_list_movie_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='public',
            field=models.CharField(choices=[('private', 'Private'), ('friends_only', 'Friends Only'), ('public', 'Public, anyone can see.')], default='public', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='list',
            field=models.ManyToManyField(to='movies.list'),
        ),
        migrations.RemoveField(
            model_name='tv_series',
            name='list',
        ),
        migrations.AddField(
            model_name='tv_series',
            name='list',
            field=models.ManyToManyField(to='movies.list'),
        ),
    ]
