# Generated by Django 4.2.5 on 2023-09-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_list_public_alter_movie_list_remove_tv_series_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='public',
            field=models.CharField(choices=[('public', 'Public, anyone can see'), ('friends_only', 'Friends Only'), ('private', 'Private')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='list',
            field=models.ManyToManyField(related_name='movies', to='movies.list'),
        ),
        migrations.AlterField(
            model_name='tv_series',
            name='list',
            field=models.ManyToManyField(related_name='tv_series', to='movies.list'),
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.list')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('tv_series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.tv_series')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
