# Generated by Django 4.2.5 on 2023-09-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_list_public_alter_movie_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
